'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
export default function Viewport({objects=[]}){const host=useRef(),api=useRef(),[wire,setWire]=useState(false),[error,setError]=useState('');
useEffect(()=>{let r;try{r=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch{setError('WebGL is unavailable in this browser. Try enabling hardware acceleration.');return;}
r.setPixelRatio(Math.min(devicePixelRatio,2));r.setClearColor(0xf3f2eb);host.current.appendChild(r.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.01,100000),model=new THREE.Group();camera.up.set(0,0,1);camera.position.set(35,-45,30);const controls=new OrbitControls(camera,r.domElement);controls.enableDamping=true;scene.add(model,new THREE.HemisphereLight(0xffffff,0x7e697a,2.5));const light=new THREE.DirectionalLight(0xfff9e9,3);light.position.set(30,-20,50);scene.add(light);const grid=new THREE.GridHelper(120,60,0xc4c0b6,0xe0ddd3);grid.rotation.x=Math.PI/2;grid.position.z=-.02;scene.add(grid);
const fit=()=>{if(!model.children.length)return;const box=new THREE.Box3().setFromObject(model),center=box.getCenter(new THREE.Vector3()),radius=Math.max(box.getSize(new THREE.Vector3()).length()/2,1),distance=radius/Math.sin(THREE.MathUtils.degToRad(camera.fov/2))/Math.min(camera.aspect,1);const dir=camera.position.clone().sub(controls.target).normalize();controls.target.copy(center);camera.position.copy(center).addScaledVector(dir,distance*1.2);camera.near=Math.max(radius/10000,.001);camera.far=Math.max(distance*100,1000);camera.updateProjectionMatrix();grid.scale.setScalar(Math.max(radius/22,.1));grid.position.set(center.x,center.y,box.min.z-radius*.005);controls.update();};
const resize=new ResizeObserver(()=>{if(!host.current)return;const{width,height}=host.current.getBoundingClientRect();r.setSize(width,height,false);camera.aspect=width/Math.max(height,1);camera.updateProjectionMatrix();});resize.observe(host.current);r.setAnimationLoop(()=>{controls.update();r.render(scene,camera);});api.current={r,scene,camera,model,fit};return()=>{resize.disconnect();r.setAnimationLoop(null);controls.dispose();scene.traverse(x=>{x.geometry?.dispose();x.material?.dispose();});r.dispose();r.domElement.remove();api.current=null;};},[]);
useEffect(()=>{const a=api.current;if(!a)return;const first=!a.model.children.length;while(a.model.children.length){const x=a.model.children[0];a.model.remove(x);x.geometry?.dispose();x.material?.dispose();}const loader=new THREE.BufferGeometryLoader();for(const item of objects){let x;if(item.kind==='mesh'){const g=loader.parse(item.mesh);g.computeVertexNormals();x=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0xb891ab,roughness:.52,metalness:.08,side:THREE.DoubleSide,wireframe:wire}));}else if(item.kind==='curve')x=new THREE.Line(new THREE.BufferGeometry().setFromPoints(item.points.map(p=>new THREE.Vector3(...p))),new THREE.LineBasicMaterial({color:0xbc146e}));else if(item.kind==='point')x=new THREE.Points(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...item.point)]),new THREE.PointsMaterial({color:0xe91b8c,size:5,sizeAttenuation:false}));if(x)a.model.add(x);}if(first)a.fit();},[objects,wire]);
function capture(){const a=api.current;if(!a)return;a.r.render(a.scene,a.camera);a.r.domElement.toBlob(blob=>{if(!blob)return;const u=URL.createObjectURL(blob),el=document.createElement('a');el.href=u;el.download='modolouge-view.png';el.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});}
return <div className="viewport-wrap"><div ref={host} className="viewport" aria-label="Interactive 3D geometry viewport"/>{(!objects.length||error)&&<div className="viewport-empty"><span className="orb">◎</span><h2>{error||'Room for possibilities.'}</h2><p>{error?'':'Your geometry will appear here after a solve.'}</p></div>}<div className="viewport-tools"><button onClick={()=>api.current?.fit()}>Fit view</button><button aria-pressed={wire} onClick={()=>setWire(!wire)}>Wireframe</button><button onClick={capture}>Save image ↗</button></div><span className="viewport-caption">PERSPECTIVE / Z UP / {objects.length} OBJECTS</span></div>;}
